### ISSUE TITLE
Board selection in Platform.IO

### ISSUE THREAD

**Issue by GeirFrimann** [QuickSpot/walter-arduino#1]
The ESP32S3 Dev Module is not available in Platform.IO. 
I have tried esp32-s3-devkitc-1, but it doesn't work.
Is there any other board that will work, or any work-around?

**Comment by daanpape** [comment]
Hi Geir,

The ESP32-S3 should work, we will test it out and reply ASAP. 

Kind regards,
Daan

**Comment by GeirFrimann** [comment]
> Hi Geir,
> 
> The ESP32-S3 should work, we will test it out and reply ASAP.
> 
> Kind regards, Daan
 The code compiles with esp32-s3-devkitc-1, but nothing is displayed in the terminal

**Comment by tomkeuper** [comment]
I have used the following configuration to compile and upload to Walter.
```
[env:esp32-s3-devkitc-1]
monitor_speed = 115200
platform = espressif32
board = esp32-s3-devkitc-1
upload_speed = 115200
framework = arduino

board_build.partitions = huge_app.csv

build_flags =
    -D ESP32
    -D ARDUINO_USB_CDC_ON_BOOT=1
```

**Comment by daanpape** [comment]
Hi Geir,

We finally had some time to test out PlatformIO and we have created this first settings file:

[walter.json](https://github.com/QuickSpot/walter-arduino/files/13583710/walter.json)

Can you please test if this also works for you?

**Comment by DeepBlue-Dev** [comment]
I tested the board definition today, and it works!

**Comment by daanpape** [comment]
@DeepBlue-Dev thank you for the confirmation. I will now close this issue.
